Script started on 2016年03月14日 (週一) 11時11分53秒
]0;F74042159@2015cpp: ~/lab1[01;32mF74042159@2015cpp[00m:[01;34m~/lab1[00m$ exit[2Plsvim .vimrc[5Pcd ..[3Plscd ..[3Plsvim lab1B.cppls[Kvim lab1B.cppls[Kcd ..[3Plscd ..vim .vimrcls[Kexit[Ksc[K[Kls
[0m[01;32mlab1B[0m  lab1B.cpp  lab1.script  README.md  Runlab1B.script
]0;F74042159@2015cpp: ~/lab1[01;32mF74042159@2015cpp[00m:[01;34m~/lab1[00m$ cat lab1.B.[Ccpp
#include<iostream>
using namespace std;

int main(){
	int n;
	cout << "input n:";
	cin >> n;
	cout << n << " ";
	while(n!=1){
		if(n%2==1)
			n = 3*n+1;
		else
			n = n/2;
		cout << n << " ";

	}
	cout << endl;
	return 0;
}
]0;F74042159@2015cpp: ~/lab1[01;32mF74042159@2015cpp[00m:[01;34m~/lab1[00m$ ./cat la[K[K[K[K[K[Kla1b[K[Kb1B
input n:12
12 6 3 10 5 16 8 4 2 1 
]0;F74042159@2015cpp: ~/lab1[01;32mF74042159@2015cpp[00m:[01;34m~/lab1[00m$ exit

Script done on 2016年03月14日 (週一) 11時14分13秒
